#Overall weather patterns
#Generated by AA on 28JUne2018

# Set working directory
setwd("/media/aakanksha/f41d5ac2-703c-4b56-a960-cd3a54f21cfb/aakanksha/Documents/Backup/PhenologyAnalysis")

dat=read.csv("Apr2011- May 2018Weatherdata .csv")
str(dat)
mms = c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec")
mms=factor(mms,levels=mms)
yr=rep(c(2011,2012,2013,2014,2015,2016,2017,2018),each=12)
mmyr = paste(mms,yr)          #Make chronologically sorted mmyyyy
mmyr=factor(mmyr,levels=mmyr)
yrs=unique(dat$Year)
nyr=length(yrs)
dat$date=paste(dat$Month,dat$Year)
timel=unique(dat$date)

#################################################################################################
#Rainfall time-series
datR=dat[!is.na(dat$Rainfall),]
RainMin = tapply(datR$Rainfall,list(datR$date),FUN = min)
RainMin=RainMin[match(mmyr, as.factor(rownames(RainMin)))]  #Correct the sequence of months and year
RainMax = tapply(datR$Rainfall,list(datR$date),FUN = max)
RainMax=RainMax[match(mmyr, as.factor(rownames(RainMax)))]  #Correct the sequence of months and year
RainMean = tapply(datR$Rainfall,list(datR$date),FUN = mean)
RainMean=RainMean[match(mmyr, as.factor(rownames(RainMean)))]  #Correct the sequence of months and year

#Graph
lbl= seq(1,length(mmyr),by=6)                    #1:length(na.omit(rownames(RainMean)))
x=1:length(mmyr)

png("Graphs//RainfallMean.png",width=1080,height=720,units = "px", pointsize = 20)
plot(x,as.vector(RainMean),xaxt="n",xlab="",ylab="Rainfall in mm",type="b",pch=20,col="navy")
#points(x,na.omit(as.vector(RainMin)),xaxt="n",type="b",pch=20,col="red",lty=2)
#points(x,na.omit(as.vector(RainMax)),xaxt="n",type="b",pch=20,col="green",lty=2)
#legend("topright", legend=c("Minimum monthly rainfall", "Mean monthly rainfall","Maximum monthly rainfall"),col=c("red", "navy","green"), lty=c(2,1,2),pch=c(20,20,20), cex=0.8)
axis(1, at=lbl, labels=mmyr[lbl],las=2)
dev.off();


png("Graphs//RainfallMaxMin.png",width=1080,height=720,units = "px", pointsize = 20)
plot(x,as.vector(RainMax),xaxt="n",xlab="",ylab="Rainfall in mm",type="b",pch=20,col="navy")
points(x,as.vector(RainMin),xaxt="n",type="b",pch=20,col="orange",lty=1)
#points(x,na.omit(as.vector(RainMax)),xaxt="n",type="b",pch=20,col="green",lty=2)
legend("topright", legend=c("Maximum monthly rainfall", "Minimum monthly rainfall"),col=c("navy", "orange"), lty=c(2,1),pch=c(20,20), cex=0.8)
axis(1, at=lbl, labels=mmyr[lbl],las=2)
dev.off();
#######################################################################################################


#Temperature time-series
library(reshape2)  #library to melt the lists

datT=dat[!is.na(dat$Temp),]
TempAvg = tapply(datT$Temp,list(datT$Date),FUN = mean)   #daily average
x=as.data.frame(melt(TempAvg))
for(i in 1:nrow(x)){
  x[i,"Month"]=datT[which(datT$Date==x[i,1])[1],"Month"]
  x[i,"Year"]=datT[which(datT$Date==x[i,1])[1],"Year"]
}

TempMax = tapply(x$value,list(paste(x$Month,x$Year)),FUN = max)
TempMax=TempMax[match(mmyr, as.factor(rownames(TempMax)))]
TempMin = tapply(x$value,list(paste(x$Month,x$Year)),FUN = min)
TempMin=TempMin[match(mmyr, as.factor(rownames(TempMin)))]
TempMean = tapply(x$value,list(paste(x$Month,x$Year)),FUN = mean)
TempMean=TempMean[match(mmyr, as.factor(rownames(TempMean)))]


#Graph
x=1:length(na.omit(names(TempMax)))
png("Graphs//Temperature.png",width=1080,height=720,units = "px", pointsize = 20)
plot(x,na.omit(as.vector(TempMax)),xaxt="n",xlab="",ylab="Temperature",type="b",pch=20,col="navy",ylim=c(min(na.omit(datT$Temp)),max(na.omit(datT$Temp))))
points(x,na.omit(as.vector(TempMin)),xaxt="n",type="b",pch=20,col="red",lty=2)
legend("topright", legend=c("Maximum average daily temperature", "Minimum average daily temperature"),col=c("navy", "red"), lty=c(2,1),pch=c(20,20), cex=0.8)
axis(1, at=lbl, labels=mmyr[lbl],las=2)
dev.off()

x=1:length(na.omit(names(TempMean)))
png("Graphs//TemperatureMean.png",width=1080,height=720,units = "px", pointsize = 20)
plot(x,na.omit(as.vector(TempMean)),xaxt="n",xlab="",ylab="Temperature",type="b",pch=20,col="navy")
#points(x,na.omit(as.vector(TempMin)),xaxt="n",type="b",pch=20,col="red",lty=2)
#legend("topright", legend=c("Maximum average daily temperature", "Minimum average daily temperature"),col=c("navy", "red"), lty=c(2,1),pch=c(20,20), cex=0.8)
axis(1, at=lbl, labels=mmyr[lbl],las=2)
dev.off()

######################################################################################################
#Irradiance time-series
library(reshape2)  #library to melt the lists

datI=dat[!is.na(dat$SolarRadiation),]
Imax = tapply(datI$SolarRadiation,list(datI$Date),FUN = max)   #daily average
x=as.data.frame(melt(Imax))
for(i in 1:nrow(x)){
  x[i,"Month"]=datT[which(datT$Date==x[i,1])[1],"Month"]
  x[i,"Year"]=datT[which(datT$Date==x[i,1])[1],"Year"]
}

Imean = tapply(x$value,list(paste(x$Month,x$Year)),FUN = mean)
Imean=Imean[match(mmyr, as.factor(rownames(Imean)))]


#Graph
x=1:length(na.omit(names(Imean)))
png("Graphs//Irradiance.png",width=1080,height=720,units = "px", pointsize = 20)
plot(x,na.omit(as.vector(Imean)),xaxt="n",xlab="",ylab="Mean monthly irradiance",type="b",pch=20,col="navy")
axis(1, at=lbl, labels=mmyr[lbl],las=2)
dev.off()

####################################################################################################

#RH time-series
library(reshape2)  #library to melt the lists

datH=dat[!is.na(dat$RH),]
RHAvg = tapply(datH$RH,list(datT$Date),FUN = mean)   #daily average
x=as.data.frame(melt(RHAvg))
for(i in 1:nrow(x)){
  x[i,"Month"]=datT[which(datT$Date==x[i,1])[1],"Month"]
  x[i,"Year"]=datT[which(datT$Date==x[i,1])[1],"Year"]
}

RHMean = tapply(x$value,list(paste(x$Month,x$Year)),FUN = mean)
RHMean=RHMean[match(mmyr, as.factor(rownames(RHMean)))]


#Graph
x=1:length(na.omit(names(RHMean)))
png("Graphs//RH.png",width=1080,height=720,units = "px", pointsize = 20)
plot(x,na.omit(as.vector(RHMean)),xaxt="n",xlab="",ylab="Average Relative Humidity",type="b",pch=20,col="navy")
axis(1, at=lbl, labels=mmyr[lbl],las=2)
dev.off()

